<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_AcceleratorLinks" Id="{a8c08e7c-c206-478b-9402-da1b879edfc5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AcceleratorLinks
VAR_INPUT

END_VAR

VAR_OUTPUT
END_VAR


VAR

    {attribute 'pytmc' := '
        pv: eEnrg:Hgvpu
        link: BEND:DMPH:400:BACT
        field: EGU GeV
    '}
    fbHgvpuElectronEnergy : FB_LREALFromEPICS;

    {attribute 'pytmc' := '
        pv: eEnrg:SXU
        link: BEND:DMPS:400:BACT
        field: EGU GeV
    '}
    fbSxuElectronEnergy : FB_LREALFromEPICS;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbHgvpuElectronEnergy();
fbSxuElectronEnergy();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>